AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'lib/**/*_test.rb'
    - 'test/**/*.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false
